## Reading the CSV

In [1]:
import pandas as pd

df = pd.read_csv('cars.csv')
df.head()

,url,price,brand,series,model,year,mileage,transmission,fuel,body,...,engine,hp,drive,condition,heavy_damage,paint_changed,fuel_consumption,fuel_tank,trade_in,seller_type
0,https://www.arabam.com/ilan/galeriden-satilik-...,1.049.000 TL,Ford,Focus,1.5 TDCi Trend X,2018.0,180.000 km,Otomatik,Dizel,Sedan,...,1401 - 1600 cm3,101 - 125 HP,Önden Çekiş,İkinci El,NaN,"1 değişen, 2 boyalı",NaN,NaN,Takasa Uygun,Galeriden
1,https://www.arabam.com/ilan/galeriden-satilik-...,555.750 TL,Ford,Focus,1.6 TDCi Collection,2010.0,357.000 km,Düz,Dizel,Hatchback/5,...,1560 cc,90 hp,Önden Çekiş,İkinci El,Hayır,5 boyalı,"4,7 lt",55 lt,Takasa Uygun,Galeriden
2,https://www.arabam.com/ilan/galeriden-satilik-...,595.000 TL,Citroen,C-Elysée,1.6 HDi Attraction,2014.0,225.000 km,Düz,Dizel,Sedan,...,1560 cc,93 hp,Önden Çekiş,İkinci El,NaN,2 boyalı,"4,3 lt",48 lt,Takasa Uygun,Galeriden
3,https://www.arabam.com/ilan/galeriden-satilik-...,2.059.000 TL,Mercedes - Benz,C,C 180 BlueEFFICIENCY AMG,2014.0,75.000 km,Otomatik,Benzin,Coupe,...,1401 - 1600 cm3,151 - 175 HP,Arkadan İtiş,İkinci El,Belirtilmemiş,Tamamı orjinal,NaN,NaN,Takasa Uygun,Galeriden
4,https://www.arabam.com/ilan/galeriden-satilik-...,1.150.000 TL,Volvo,S60,1.6 D Advance,2014.0,193.000 km,Otomatik,Dizel,Sedan,...,1401 - 1600 cm3,101 - 125 HP,Önden Çekiş,İkinci El,NaN,1 değişen,NaN,NaN,Takasa Uygun,Galeriden

## Cleaning the Data

### We want to clean the price, mileage, and year data to convert them to floats and drop the unrealistic data.

In [2]:
df = df.drop_duplicates(subset=["url"]).copy()

In [3]:
df["price"] = (
    df["price"]
    .str.replace(" TL", "", regex=False)
    .str.replace(".", "", regex=False)
    .astype(float)
)

df = df[(df["price"] < 20000000) & (df["price"] > 100000)].copy()

df["price"].describe()

count    4.195800e+04
mean     1.102598e+06
std      1.097180e+06
min      1.025000e+05
25%      5.200000e+05
50%      8.500000e+05
75%      1.315000e+06
max      1.998500e+07
Name: price, dtype: float64

In [4]:
df["mileage"] = df["mileage"].str.replace(" km", "", regex=False).str.replace(".", "", regex=False).astype(float)

df = df[
    (df["year"] >= 1980) &
    (df["year"] <= 2026) &
    (df["mileage"] > 0) &
    (df["mileage"] < 1_000_000)
].copy()

df["mileage"].describe()

count     41914.000000
mean     190561.728062
std      103468.379401
min        5080.000000
25%      115000.000000
50%      185000.000000
75%      257000.000000
max      999999.000000
Name: mileage, dtype: float64

In [5]:
df['heavy_damage'] = df['heavy_damage'].fillna('Belirtilmemiş')
df["heavy_damage"].describe()

count             41914
unique                3
top       Belirtilmemiş
freq              26616
Name: heavy_damage, dtype: object

In [6]:
df = df.reset_index(drop=True)
df.head()

,url,price,brand,series,model,year,mileage,transmission,fuel,body,...,engine,hp,drive,condition,heavy_damage,paint_changed,fuel_consumption,fuel_tank,trade_in,seller_type
0,https://www.arabam.com/ilan/galeriden-satilik-...,1049000.0,Ford,Focus,1.5 TDCi Trend X,2018.0,180000.0,Otomatik,Dizel,Sedan,...,1401 - 1600 cm3,101 - 125 HP,Önden Çekiş,İkinci El,Belirtilmemiş,"1 değişen, 2 boyalı",NaN,NaN,Takasa Uygun,Galeriden
1,https://www.arabam.com/ilan/galeriden-satilik-...,555750.0,Ford,Focus,1.6 TDCi Collection,2010.0,357000.0,Düz,Dizel,Hatchback/5,...,1560 cc,90 hp,Önden Çekiş,İkinci El,Hayır,5 boyalı,"4,7 lt",55 lt,Takasa Uygun,Galeriden
2,https://www.arabam.com/ilan/galeriden-satilik-...,595000.0,Citroen,C-Elysée,1.6 HDi Attraction,2014.0,225000.0,Düz,Dizel,Sedan,...,1560 cc,93 hp,Önden Çekiş,İkinci El,Belirtilmemiş,2 boyalı,"4,3 lt",48 lt,Takasa Uygun,Galeriden
3,https://www.arabam.com/ilan/galeriden-satilik-...,2059000.0,Mercedes - Benz,C,C 180 BlueEFFICIENCY AMG,2014.0,75000.0,Otomatik,Benzin,Coupe,...,1401 - 1600 cm3,151 - 175 HP,Arkadan İtiş,İkinci El,Belirtilmemiş,Tamamı orjinal,NaN,NaN,Takasa Uygun,Galeriden
4,https://www.arabam.com/ilan/galeriden-satilik-...,1150000.0,Volvo,S60,1.6 D Advance,2014.0,193000.0,Otomatik,Dizel,Sedan,...,1401 - 1600 cm3,101 - 125 HP,Önden Çekiş,İkinci El,Belirtilmemiş,1 değişen,NaN,NaN,Takasa Uygun,Galeriden

## Concatenate Brand & Series

### I decided to concatenate these two since each brand's series are special to that brand.

In [7]:
df["brand_series"] = df["brand"] + "_" + df["series"]
df["brand_series"].describe()

count              41914
unique               292
top       Toyota_Corolla
freq                1901
Name: brand_series, dtype: object

## Encoding Brand & Series

### We want to encode these to labels for our model to understand since working with strings does not make sense.

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["brand_series_encoded"] = le.fit_transform(df["brand_series"])
df["heavy_damage_encoded"] = le.fit_transform(df["heavy_damage"])
print(df["brand_series_encoded"].head())
print(df["heavy_damage_encoded"].head())

0     76
1     76
2     27
3    147
4    281
Name: brand_series_encoded, dtype: int64
0    0
1    2
2    0
3    0
4    0
Name: heavy_damage_encoded, dtype: int64

## Creating the Train & Test Splits

In [9]:
X = df[['brand_series_encoded', 'year', 'mileage', "heavy_damage_encoded"]]
y = df["price"]

print(X.head())
print(y.head())

   brand_series_encoded    year   mileage  heavy_damage_encoded
0                    76  2018.0  180000.0                     0
1                    76  2010.0  357000.0                     2
2                    27  2014.0  225000.0                     0
3                   147  2014.0   75000.0                     0
4                   281  2014.0  193000.0                     0
0    1049000.0
1     555750.0
2     595000.0
3    2059000.0
4    1150000.0
Name: price, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

## Training the baseline decision tree

In [11]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)
print("Decision Tree MAE:", mean_absolute_error(y_test, y_pred))

Decision Tree MAE: 169626.583104696

## Training the baseline XGBoost

In [12]:
from xgboost import XGBRegressor

xgb = XGBRegressor(n_estimators=500, learning_rate=0.05, max_depth=6)
xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)
print("XGBoost MAE:", mean_absolute_error(y_test, y_pred_xgb))

XGBoost MAE: 145543.26313973407

## Training the baseline LightGBM

In [ ]:
from lightgbm import LGBMRegressor

lgbm = LGBMRegressor(
    objective="regression",
    n_estimators=700,
    learning_rate=0.05,
    num_leaves=31,
    random_state=42,
    verbose=-1
)

categorical_features = ["brand_series_encoded", "heavy_damage_encoded"]
lgbm.fit(X_train, y_train, categorical_feature=categorical_features)

y_pred_lgbm = lgbm.predict(X_test)
print("LightGBM MAE:", mean_absolute_error(y_test, y_pred_lgbm))

LightGBM MAE: 135583.3247476554

## Grid Search for tuning the hyperparameters of the LightGBM

In [14]:
from sklearn.model_selection import GridSearchCV

lgbm_param_grid = {
    "n_estimators": [300, 500, 700],
    "learning_rate": [0.03, 0.05, 0.07],
    "num_leaves": [15, 31, 63],
    "max_depth": [-1, 6, 10]
}

lgbm_search = GridSearchCV(
    LGBMRegressor(objective="regression", random_state=42, verbose=-1),
    lgbm_param_grid,
    cv=5,
    scoring="neg_mean_absolute_error",
    verbose=1,
    n_jobs=-1
)

lgbm_search.fit(X_train, y_train, categorical_feature=categorical_features)

print("Best LightGBM params:", lgbm_search.best_params_)
print("Best LightGBM MAE:", -lgbm_search.best_score_)

Fitting 5 folds for each of 81 candidates, totalling 405 fits
Best LightGBM params: {'learning_rate': 0.05, 'max_depth': -1, 'n_estimators': 700, 'num_leaves': 15}
Best LightGBM MAE: 132136.21137858424

## Training the tuned LightGBM on the test set

In [ ]:
best_lgbm = LGBMRegressor(
    objective="regression",
    learning_rate=0.05,
    max_depth=-1,
    n_estimators=700,
    num_leaves=15,
    random_state=42,
    verbose=-1
)

best_lgbm.fit(X_train, y_train, categorical_feature=categorical_features)

y_pred_best_lgbm = best_lgbm.predict(X_test)
print("Tuned LightGBM Test MAE:", mean_absolute_error(y_test, y_pred_best_lgbm))

Tuned LightGBM Test MAE: 135420.38347516817

## Grid Search for tuning the hyperparameters of the XGBoost

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [300, 400, 500],
    "learning_rate": [0.03, 0.05, 0.07],
    "max_depth": [5, 6, 7]
}

search = GridSearchCV(XGBRegressor(), param_grid, cv=5, scoring="neg_mean_absolute_error", verbose=1)
search.fit(X_train, y_train)

print("Best params:", search.best_params_)
print("Best MAE:", -search.best_score_)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best params: {'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 400}
Best MAE: 144140.20385317254

In [14]:
best_xgb = XGBRegressor(learning_rate=0.05, max_depth=7, n_estimators=400)
best_xgb.fit(X_train, y_train)

y_pred_best = best_xgb.predict(X_test)
print("Tuned XGBoost MAE:", mean_absolute_error(y_test, y_pred_best))

Tuned XGBoost MAE: 143283.89766724696

## Bargain Finder for finding the listings where the listed price is a lot lower than our predicted price

In [15]:
df['predicted_price'] = best_xgb.predict(X)
df['discount'] = df['predicted_price'] - df['price']

bargains = df[['url', 'brand_series', 'year', 'mileage', 'price', 'predicted_price', 'discount', 'heavy_damage', 'paint_changed']]
bargains = bargains.sort_values('discount', ascending=False)
bargains.head(20)

,url,brand_series,year,mileage,price,predicted_price,discount,heavy_damage,paint_changed
2952,https://www.arabam.com/ilan/galeriden-satilik-...,BMW_5 Serisi,1993.0,29000.0,244950.0,4596975.50,4352025.50,Belirtilmemiş,Belirtilmemiş
2030,https://www.arabam.com/ilan/galeriden-satilik-...,Citroen_AMİ,2025.0,6001.0,480000.0,4819945.00,4339945.00,Belirtilmemiş,Belirtilmemiş
420,https://www.arabam.com/ilan/galeriden-satilik-...,Citroen_AMİ,2025.0,6001.0,519000.0,4819945.00,4300945.00,Belirtilmemiş,Tamamı orjinal
5533,https://www.arabam.com/ilan/galeriden-satilik-...,Mercedes - Benz_C,2023.0,16000.0,4345000.0,8600918.00,4255918.00,Belirtilmemiş,Belirtilmemiş
5015,https://www.arabam.com/ilan/galeriden-satilik-...,Mercedes - Benz_C,2023.0,16500.0,4375000.0,8600918.00,4225918.00,Belirtilmemiş,Belirtilmemiş
39904,https://www.arabam.com/ilan/galeriden-satilik-...,Porsche_Taycan,2023.0,29900.0,10250000.0,14403006.00,4153006.00,Belirtilmemiş,Tamamı orjinal
31876,https://www.arabam.com/ilan/galeriden-satilik-...,Audi_A6,2025.0,7000.0,5195000.0,8693523.00,3498523.00,Belirtilmemiş,2 değişen
5766,https://www.arabam.com/ilan/galeriden-satilik-...,Mercedes - Benz_CLA,2024.0,6100.0,3649000.0,6973065.50,3324065.50,Belirtilmemiş,Tamamı orjinal
24056,https://www.arabam.com/ilan/galeriden-satilik-...,Peugeot_508,2012.0,109000.0,869000.0,4130402.00,3261402.00,Belirtilmemiş,1 boyalı
25445,https://www.arabam.com/ilan/galeriden-satilik-...,Peugeot_508,2012.0,138000.0,765000.0,3868059.00,3103059.00,Belirtilmemiş,"3 değişen, 6 boyalı"
40829,https://www.arabam.com/ilan/galeriden-satilik-...,Porsche_Taycan,2021.0,36000.0,7050000.0,10144434.00,3094434.00,Belirtilmemiş,Tamamı orjinal
30501,https://www.arabam.com/ilan/galeriden-satilik-...,Audi_A6,2024.0,45000.0,5750000.0,8830462.00,3080462.00,Belirtilmemiş,Tamamı orjinal
39622,https://www.arabam.com/ilan/galeriden-satilik-...,Porsche_Taycan,2022.0,32000.0,9750000.0,12760026.00,3010026.00,Belirtilmemiş,Tamamı orjinal
30301,https://www.arabam.com/ilan/galeriden-satilik-...,Audi_A6,2019.0,300000.0,3125000.0,6118540.00,2993540.00,Belirtilmemiş,3 boyalı
3043,https://www.arabam.com/ilan/galeriden-satilik-...,BMW_5 Serisi,2001.0,160000.0,780000.0,3683938.25,2903938.25,Belirtilmemiş,"3 değişen, 6 boyalı"
5954,https://www.arabam.com/ilan/galeriden-satilik-...,Mercedes - Benz_C,2023.0,8000.0,4250000.0,7112081.50,2862081.50,Belirtilmemiş,Tamamı orjinal
16166,https://www.arabam.com/ilan/galeriden-satilik-...,Renault_Clio,2022.0,6100.0,1299900.0,4073265.00,2773365.00,Belirtilmemiş,Tamamı orjinal
29191,https://www.arabam.com/ilan/galeriden-satilik-...,Audi_S,2023.0,47500.0,4100000.0,6871120.00,2771120.00,Belirtilmemiş,"2 değişen, 1 boyalı, 1 lokal boyalı"
5799,https://www.arabam.com/ilan/galeriden-satilik-...,Mercedes - Benz_EQE,2024.0,17000.0,4780000.0,7318008.50,2538008.50,Belirtilmemiş,Tamamı orjinal
24370,https://www.arabam.com/ilan/galeriden-satilik-...,Citroen_AMİ,2023.0,25078.0,404000.0,2876925.25,2472925.25,Belirtilmemiş,Tamamı orjinal